# Miyadaiku config file

# Base URL of the site
site_url: https://www.python.jp/

# Title of the site
site_title: python.jp

# Default language code
lang: ja

# Default charset
charset: utf-8

# Default timezone
timezone: Asia/Tokyo

# List of site theme
themes:
  - miyadaiku.themes.pygments
  - miyadaiku.themes.bootstrap4
  - miyadaiku.themes.fontawesome
  - miyadaiku.themes.docutils_html5

ga_tracking_id: UA-34175846-1


imports: utils.html
